apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soniq.fullname" . }}
  labels:
    {{- include "soniq.labels" . | nindent 4 }}
type: Opaque
stringData:
  SONIQ_MCP_DEFAULT_ROOM: {{ .Values.secret.defaultRoom | default "" | quote }}
